package com.golapp.forestquest.staff

import com.golapp.forestquest.R

val monsterList = listOf(
    R.drawable.icon1,
    R.drawable.icon2,
    R.drawable.icon3,
    R.drawable.icon4,
    R.drawable.icon5,
    R.drawable.icon6,
    R.drawable.icon7,
    R.drawable.icon8,
    R.drawable.icon9,
    R.drawable.icon10,
    R.drawable.icon11,
    R.drawable.icon12,
    R.drawable.icon13,
    R.drawable.icon14,
    R.drawable.icon15,
    R.drawable.icon16,
    R.drawable.icon18,
    R.drawable.icon19,
    R.drawable.icon20,
    R.drawable.icon21,
    R.drawable.icon22,
    R.drawable.icon23,
    R.drawable.icon24,
    R.drawable.icon25,
    R.drawable.icon26,
    R.drawable.icon27,
    R.drawable.icon28,
    R.drawable.icon29,
    R.drawable.icon30,
    R.drawable.icon31,
    R.drawable.icon32,
    R.drawable.icon33,
    R.drawable.icon34,
    R.drawable.icon35,
    R.drawable.icon36,
    R.drawable.icon37,
    R.drawable.icon38,
    R.drawable.icon39,
    R.drawable.icon40,
    R.drawable.icon41,
    R.drawable.icon42,
    R.drawable.icon43,
    R.drawable.icon44,
    R.drawable.icon45,
    R.drawable.icon46,
    R.drawable.icon47,
    R.drawable.icon48
)